Store/Models/Brand.cs
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Store.Models
{
    public class Brand
    {
        [Key]
        public int Id { get; set; }
        
        [Required]
        [Display(Name="Name")]
        public string Name { get; set; }

        public string PhotoPath { get; set; }
        [Display(Name = "Logo")]
        [NotMapped]
        public IFormFile Photo { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        public virtual List<Product> Products { get; set; }
    }
}

Store/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [Display(Name = "Name")]
        public string Name { get; set; }

    }
}

Store/Models/Color.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Color
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name="Name")]
        public string Name { get; set; }
    }
}

Store/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Order
    {
        public int Id { get; set; }
        public string ChargeId { get; set; }

        public bool IsSend { get; set; } = false;

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        [Required]
        public DateTime? OrderDate { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/DD/YYYY}")]
        public DateTime? OrderSendDate { get; set; } = null;

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "Adres 1")]
        public string Address1 { get; set; }

        [Display(Name = "Adres 2")]
        public string Address2 { get; set; }

        public string Email { get; set; }

        [Required]
        [Display(Name ="City")]
        public string City { get; set; }

        [Required]
        [Display(Name = "Post Code")]
        public string PostCode { get; set; }

        public int? UserId { get; set; }
        public User User { get; set; }

        public ICollection<OrderProduct> OrderProducts{ get; set; }

    }
}

Store/Models/Stock.cs
using System.ComponentModel.DataAnnotations;

namespace Store.Models
{
    public class Stock
    {
        public int Id { get; set; }

        [Required]
        [Display(Name="Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Quantity")]
        public int Qty { get; set; }

        [Required]
        [Display(Name = "ProductId")]
        public int ProductId { get; set; }

        public Product Product { get; set; }

        public bool IsLastElementOrdered { get; set; } = false;


    }
}

Store/Controllers/API/AdministrationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Store.Models;
using System.Linq;

namespace Store.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class AdministrationController : ControllerBase
    {
        private readonly StoreContext _context;
        private readonly IMapper _mapper;


        public AdministrationController(StoreContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }


        [HttpDelete]
        [Route("{id:int}")]
        public IActionResult DeleteUser([FromRoute] int id)
        {
            var userInDb = _context.Users.SingleOrDefault(x => x.Id.Equals(id));

            if (userInDb == null)
            {
                return NotFound();
            }

            _context.Users.Remove(userInDb);
            _context.SaveChanges();

            System.Diagnostics.Debug.WriteLine("Usunieto usera");
            return Ok();
            
        }


        [HttpGet]
        public IActionResult GetUsers()
        {
            var users = _context.Users.ToList();

            return Ok(users);
        }


        [HttpGet]
        [Route("{id:int}")]
        public IActionResult GetUser([FromRoute] int id)
        {
            var userInDb = _context.Users.SingleOrDefault(c => c.Id.Equals(id));


            if (userInDb == null)
                return NotFound();

            return Ok(userInDb);
        }


        [HttpPost]
        public IActionResult PostUser([FromBody] User user)
        {
            _context.Users.Add(user);
            _context.SaveChanges();

            return Ok();
        }

    }
}

Store/Controllers/API/ProductController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Models;
using System.Threading.Tasks;

namespace Store.Controllers.API
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProductController : ControllerBase
    {

        private readonly StoreContext _context;
        private readonly IMapper _mapper;

        public ProductController(StoreContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }


        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var products = await _context.Products.ToListAsync();

            return Ok(products);
        }

        [HttpGet]
        [Route("{id:int}")]
        public async Task<IActionResult> GetProduct([FromRoute] int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(x => x.Id.Equals(id));

            return Ok(product);
        }

        [HttpPost]
        public async Task<IActionResult> Post([FromBody] Product product)
        {
            if (product == null)
            {
                return Conflict("Something wrong");
            }


            _context.Products.Add(product);
            await _context.SaveChangesAsync();

            return Ok(product);

        }

        [HttpPut]
        public async Task<IActionResult> Put([FromBody] Product product)
        {
            var productInDb = await _context.Products.FirstOrDefaultAsync(x => x.Id == product.Id);

            if (productInDb == null)
            {
                return Conflict("Something wrong");
            }

            _mapper.Map(product, productInDb);


            _context.Products.Update(productInDb);
            await _context.SaveChangesAsync();

            return Ok(product);

        }

        //[HttpDelete]
        //[Route("{id:int}")]

        //public async Task<IActionResult> DeleteProduct([FromRoute] int id)
        //{
        //    var productInDb = await _context.Products.SingleOrDefaultAsync(x => x.Id.Equals(id));

        //    if (productInDb == null)
        //    {
        //        return NotFound();
        //    }

        //    _context.Products.Remove(productInDb);
        //    await _context.SaveChangesAsync();

        //    return Ok();
        //}

        //[HttpDelete]
        //[Route("{id:int}")]

        //public async Task<IActionResult> DeleteStock(int id)
        //{
        //    var productInDb = await _context.Stock.SingleOrDefaultAsync(x => x.Id.Equals(id));

        //    if (productInDb == null)
        //    {
        //        return NotFound();
        //    }

        //    _context.Stock.Remove(productInDb);
        //    await _context.SaveChangesAsync();

        //    return Ok();
        //}
    }
}

Store/Controllers/AdministrationController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Store.Models;
using Store.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Store.Controllers
{
    [Authorize(Roles ="Admin")]

    public class AdministrationController : Controller
    {

        private readonly RoleManager<Role> _roleManager;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IMapper _mapper;

        private readonly StoreContext _context;

        public AdministrationController(RoleManager<Role> roleManager, UserManager<User> userManager, StoreContext context,
            IWebHostEnvironment hostEnvironment, IMapper mapper, SignInManager<User> signInManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _signInManager = signInManager;
            _hostEnvironment = hostEnvironment;
            _mapper = mapper;
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Users()
        {
            var users = await _context.Users.ToListAsync();

            if (_signInManager.IsSignedIn(User))
            {
                var userName = User.Identity.Name;
                var user = await _userManager.FindByNameAsync(userName);

                users.Remove(user);
            }

            return View(users);
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View(new CreateRoleViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new Role
                {
                    Name = model.RoleName
                };

                var result = await _roleManager.CreateAsync(role);


                if (result.Succeeded)
                {
                    System.Diagnostics.Debug.WriteLine($"Roles have been created {model.RoleName}");

                    return RedirectToAction("Roles");
                }

                foreach (var error in result.Errors)
                {
                    System.Diagnostics.Debug.WriteLine($"Failed attempt to create a role {model.RoleName}");

                    ModelState.AddModelError("",error.Description);
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Roles()
        {
            var roles = _roleManager.Roles;

            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(int id)
        {
            var role = await _roleManager.FindByIdAsync(id.ToString());

            if (role==null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return NotFound();
            }

            var model = new EditRoleViewModel
            {
                Id = id,
                RoleName = role.Name,
                Users = new List<User>()
            };

            foreach (var user in await _userManager.GetUsersInRoleAsync(role.Name))
            {
                model.Users.Add(user);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                System.Diagnostics.Debug.WriteLine($"Role ID not found = {model.Id}");
                return NotFound();
            }

            role.Name = model.RoleName;
            var result = await _roleManager.UpdateAsync(role);

            if (result.Succeeded)
            {
                System.Diagnostics.Debug.WriteLine($"Role with id edited = {model.Id}");

                return RedirectToAction("ListRoles");
            }

            foreach (var error in result.Errors)
            {
                System.Diagnostics.Debug.WriteLine($"Unsuccessful audition of the role of the id = {model.Id}");

                ModelState.AddModelError("", error.Description);
            }

            model.Users = new List<User>();

            foreach (var user in await _userManager.GetUsersInRoleAsync(role.Name))
            {
                model.Users.Add(user);
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(int roleId)
        {
            ViewBag.roleId = roleId;

            var role = await _roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";

                return NotFound();
            }

            var model = new List<UserRoleViewModel>();

            var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);

            foreach (var user in _userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    IsSelected = await IsInRoleAsync(user,role.Name)
                };

                model.Add(userRoleViewModel);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, int roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId.ToString());

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return NotFound();
            }

            bool ifSucceeded = false;

            for (int i = 0; i < model.Count; i++)
            {
                var user = await _userManager.FindByIdAsync(model[i].UserId.ToString());

                if (model[i].IsSelected && !(await IsInRoleAsync(user, role.Name)))
                {
                    var result = await _userManager.AddToRoleAsync(user, role.Name);
                    if (result.Succeeded)
                    {
                        ifSucceeded = true;
                    }
                }
                else if (!model[i].IsSelected && await IsInRoleAsync(user, role.Name))
                {
                    ifSucceeded = await DeleteRoleAsync(user, role.Id);
                }

                if (ifSucceeded)
                {
                    if (i < model.Count - 1)
                    {
                        continue;
                    }

                    return RedirectToAction("EditRole", new {id = roleId});
                }
            }

            return RedirectToAction("EditRole", new { id = roleId });
        }

        private async Task<bool> IsInRoleAsync(User user, string roleName)
        {
            var usersInRole = await _userManager.GetUsersInRoleAsync(roleName);

            foreach (var userInRole in usersInRole)
            {
                if (userInRole.Id == user.Id)
                {
                    return true;
                }
            }

            return false;
        }

        private async Task<bool> DeleteRoleAsync(User user, int roleId)
        {

            var userRole = new IdentityUserRole<int>
            {
                UserId = user.Id,
                RoleId = roleId
            };

            _context.UserRoles.Remove(userRole);
            await _context.SaveChangesAsync();


            return true;
        }


        [HttpGet]
        public async Task<IActionResult> UserDetails(int id)
        {
            var user = await _context.Users
                .Include(u => u.Gender)
                .SingleAsync(x => x.Id.Equals(id));


            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(int id)
        {
            var user = await _context.Users
                .Include(x => x.Gender)
                .SingleOrDefaultAsync(x => x.Id.Equals(id));

            if (user == null)
                return NotFound();

            var viewModel = new UserFormViewModel
            {
                Genders = _context.Genders.ToList(),
                GenderId = user.GenderId,
                PhoneNumber = user.PhoneNumber,
                Id = user.Id,
                LastName = user.LastName,
                FirstName = user.FirstName,
                PhotoPath = user.PhotoPath
            };

            return View("EditUser", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(UserFormViewModel model)
        {

            if (ModelState.IsValid)
            {
                string uniqueFileName = null;

                if (model.Photo != null)
                {
                    string uploadsFolder = Path.Combine(_hostEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    await model.Photo.CopyToAsync(new FileStream(filePath, FileMode.Create));
                }


                var user = _userManager.FindByIdAsync(model.Id.ToString()).Result;

                _mapper.Map(model, user);

Store/Views/Administration/Category.cshtml
@model IEnumerable<Store.Models.Category>

@{
    ViewData["Title"] = "Category";
}


@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}


<br />
<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("AddCategory", "Administration")'">
    Add a new category
</button>
<br />
<br />


<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditCategory", new { id = item.Id })
            </td>
            <td>
                @Html.ActionLink("Delete", "DeleteCategory", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

Store/Views/Administration/CategoryForm.cshtml
@model Store.Models.Category

@{
    ViewData["Title"] = "Category Form";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<hr />
<br />


@using (Html.BeginForm("SaveCategory", "Administration"))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary()
    <div class="form-row">
        <div class="form-group col-md-4">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
    </div>

    <br />
    if (Model.Name == null)
    {
        <button type="submit" class="btn btn-primary">Add</button>
    }
    else
    {
        @Html.HiddenFor(x=>x.Id)
        <button type="submit" class="btn btn-primary">Save</button>

    }
}

<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Category", "Administration")'">
    Cancel do listy
</button>

Store/Views/Administration/Color.cshtml
@model IEnumerable<Store.Models.Color>

@{
    ViewData["Title"] = "Color";
}
@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<br />
<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("AddColor", "Administration")'">
    Add new color
</button>
<br />
<br />


<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditColor", new { id = item.Id })
                </td>
                <td>
                    @Html.ActionLink("Delete", "DeleteColor", new { id = item.Id })
                </td>

            </tr>
        }
    </tbody>
</table>

Store/Views/Administration/ColorForm.cshtml
@model Store.Models.Color

@{
    ViewData["Title"] = "Color Form";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<hr />
<br />

@using (Html.BeginForm("SaveColor", "Administration"))
{
    @Html.AntiForgeryToken()

    <div class="text-danger">@Html.ValidationSummary()</div>
    <div class="form-row">
        <div class="form-group col-md-3">
            @Html.LabelFor(x => x.Name)
            @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Name)
        </div>
    </div>

    <br />
    {
        if (Model.Name == null)
        {
            <button type="submit" class="btn btn-primary">Add</button>
        }
        else
        {
            @Html.HiddenFor(x=>x.Id)
            <button type="submit" class="btn btn-primary">Save</button>

        }
    }
}
<br />

<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Color", "Administration")'">
    Cancel do listy
</button>

Store/Views/Administration/CreateRole.cshtml
@model Store.ViewModels.CreateRoleViewModel
@{
    ViewData["Title"] = "Create new role";
}
@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}
<br />

<h1>Creta new role</h1>
<br />
<hr />


@using (Html.BeginForm("CreateRole", "Administration"))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary()
    </div>
    <div class="form-group">
        @Html.LabelFor(u => u.RoleName)
        @Html.TextBoxFor(u => u.RoleName, new { @class = "form-control" })
        @Html.ValidationMessageFor(u => u.RoleName)
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
    <a class="btn btn-danger"
       asp-controller="Administration" asp-action="Roles">
        Cancel
    </a>

}

Store/Views/Administration/EditStock.cshtml
@model Store.Models.Stock
@{
    ViewData["Title"] = "Edit";
}

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}

    <form id="myForm">
        @Html.ValidationSummary()

        <div class="form-row">
            <div class="form-group col-md-2">
                @Html.LabelFor(x => x.Name)
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-2">
                @Html.LabelFor(x => x.Qty)
                @Html.TextBoxFor(x => x.Qty, new { @class = "form-control" })
            </div>
        </div>
        @Html.HiddenFor(x => x.ProductId)
        @Html.HiddenFor(x => x.Id)


        <br />
        <button id="save" type="submit" class="btn btn-primary">Save</button>

    </form>

<br />


<button type="button" class="btn btn-dark"
        onclick="location.href = '@Url.Action("Stock", "Administration", new { id = Model.ProductId })'">
    Cancel do listy
</button>



@section scripts{

    <script>
        //poprawić ten skrypt trzeba bo raz działa a raz nie
        $(document).ready(function () {
            $('#save').click(function () {
                $.validator.unobtrusive.parse(myForm);
                if ($(myForm).valid()) {
                    var data = $(myForm).serialize()

                    var ajaxConfig = {
                        type: "POST",
                        url: "/Administration/Stock",
                        data: data,
                        success: function (response) {
                            window.location.replace("/Administration/Stock/".concat('@Model.ProductId'));
                        },
                        error: function (xhr, status) {
                            alert('Something went wrong :///');
                        }
                    }
                    $.ajax(ajaxConfig);
                }
            });
        });
    </script>

}

Store/Views/Administration/OrderDetails.cshtml
@model Store.Models.Order
@{
    ViewData["Title"] = "Details of the order " + Model.Id;
}
@{decimal priceSum = 0; }

@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}

<br />
<h1>Details of the order @Model.Id</h1>
<div class="container">
    @if (!Model.IsSend)
    {

        <div class="row">
            <div class="col-md-10">
                <button type="button" class="btn btn-danger" style="margin-right:20px;"
                        onclick="location.href = '@Url.Action("CancelOrder", "Administration", new { id = Model.Id })'">
                    Cancel
                </button>

                <button type="button" class="btn btn-success"
                        onclick="location.href = '@Url.Action("SentOrder", "Administration", new { id = Model.Id })'">
                    Send
                </button>
            </div>
            <img src="~/images//wrong.svg" width="40" />

        </div>
    }
    else
    {
        <div class="row">
            <div class="col-md-10">

            </div>
            <img src="~/images//tick.webp" width="40" />

        </div>
    }
</div>
<br />
<br />

<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
                User
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostCode)
            </th>
            <th>
                ChargeId
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.User.UserName)
            </td>
            <td>
                @if (Model.FirstName != null)
                {
                    @Html.DisplayFor(modelItem => Model.FirstName)
                }
            </td>
            <td>
                @if (Model.LastName != null)
                {
                    @Html.DisplayFor(modelItem => Model.LastName)
                }
            </td>
            <td>
                @if (Model.Address1 != null)
                {
                    @Html.DisplayFor(modelItem => Model.Address1)
                }
            </td>
            <td>
                @if (Model.Address2 != null)
                {
                    @Html.DisplayFor(modelItem => Model.Address2)
                }
            </td>
            <td>
                @if (Model.City != null)
                {
                    @Html.DisplayFor(modelItem => Model.City)
                }
            </td>
            <td>
                @if (Model.PostCode != null)
                {
                    @Html.DisplayFor(modelItem => Model.PostCode)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.ChargeId)
            </td>
        </tr>
    </tbody>
</table>

<br />
<h2>Order content</h2>
<p>Number of items: @Model.OrderProducts.Count</p>


<table class="table table-striped table-condensed">
    <thead>
        <tr>
            <th>
            </th>
            <th>
                Item
            </th>
            <th>
                Size
            </th>
            <th>
                Cena
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderProducts)
        {
            var product = item.Stock.Product;

            <tr>
                <td>
                    <img src="~/images/@product.PhotoPath" alt="Product img" height="40" />
                </td>

                <td>
                    @product.Brand.Name @product.Name
                </td>

                <td>
                    @item.Qty
                </td>

                <td>
                    @item.Stock.Name

                    @if (product.CategoryId == 1)
                    {
                        @Html.Raw("US");
                    }
                </td>

                <td>
                    @{
                        var cost = item.Qty * product.Price;
                    }
                    @cost
                </td>
            </tr>

            priceSum += product.Price * item.Qty;
        }

    </tbody>

</table>
<p>Total : @priceSum</p>







<br />
<button type="button" class="btn btn-dark" style="margin-top:20px;"
        onclick="location.href = '@Url.Action("Orders", "Administration")'">
    Cancel do listy
</button>

Store/Views/Administration/Roles.cshtml
@model IEnumerable<Store.Models.Role>
@{
    ViewData["Title"] = "Roles";
}
@{
    await Html.RenderPartialAsync("Partial/_nav_product");
}

<br />

@if (Model.Any())
{
    <a class="btn btn-dark mb-3"
       asp-controller="Administration" asp-action="CreateRole">
        Add
    </a>


    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Id: @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a class="btn btn-primary" asp-controller="Administration" asp-action="EditRole" asp-route-id="@role.Id">
                    Edit
                </a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>

        </div>
    }
}
else
{

    <div class="card">
        <div class="card-header">
            There are no roles
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create them
            </h5>
            <a class="btn btn-primary"
               asp-controller="Administration" asp-action="CreateRole">
                Create a role
            </a>
        </div>
    </div>


}